run:
	pdflatex poster
	bibtex poster
	pdflatex poster
	pdflatex poster
	pdflatex poster

clean:
	rm -f *.lof *.log *.lot *.aux *.toc *.blg *.out *.bbl *.acn *.xdy *.glo *.synctex.gz *.gnuplot *.table *~ plots/temp.* *.snm *.nav
